# Generated by Django 3.1.5 on 2021-01-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default-profile.jpg', upload_to='profile_pics', verbose_name='profile pic'),
        ),
    ]
