# Generated by Django 3.1.5 on 2021-01-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='band',
            name='img',
            field=models.ImageField(default='default-band.jpg', upload_to='bands_pics', verbose_name='foto'),
        ),
    ]
