# Generated by Django 3.1.5 on 2021-01-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20210112_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='img',
            field=models.ImageField(blank=True, default='default-band.jpg', null=True, upload_to='bands_pics', verbose_name='foto'),
        ),
    ]
